version: '3.8'

services:
  log-generator:
    image: log-generator:1.0.0
    environment:
      - LOGFILE=/logs/cleaned_logs.txt
      - SPEED=7
    volumes:
      - ../go_pipeline/log_generator/cleaned_logs.txt:/logs/cleaned_logs.txt:ro
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 64M
